name: Data Generation

on:
  push:
    branches:
      - i200555
  #schedule:
  #  - cron: '0 */12 * * *'  # Run every 12 hours

jobs:
  generate_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9  # Change to 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set Git user information
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Pull data with DVC
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GOOGLE_DRIVE }}
      run: |
        dvc pull

    - name: Run data generation script
      run: |
        python append_data.py
      env:
        DATA_FILE_PATH: sensor_data.csv
#Fixed some bugs
    - name: DVC Add and Commit
      run: |
        git add . 
        git commit -m "DVC commit for data file"

    - uses: iterative/setup-dvc@v1
    - name: Push data with DVC
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GOOGLE_DRIVE }}
      run: |
        dvc add sensor_data.csv
        git add .
        git commit -m "DVC commit for data file"
        git push
        dvc push